# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Accreditation.create([
  { :individual_income => nil, :joint_income => nil, :net_worth => nil, :experience => nil, :agree => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Authentication.create([
  { :user_id => nil, :provider => nil, :uid => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Campaign.create([
  { :biz_name => nil, :blurb => nil, :about => nil, :why_join => nil, :location_id => nil, :campaign_starter_id => nil, :host_id => nil, :created_at => nil, :updated_at => nil, :successful => nil, :expires => nil }
], :without_protection => true )



Charge.create([
  { :full_name => nil, :last4 => nil, :user_id => nil, :token => nil, :location_id => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Comment.create([
  { :content => nil, :user_id => nil, :created_at => nil, :updated_at => nil, :commentable_id => nil, :commentable_type => nil }
], :without_protection => true )



Event.create([
  { :title => "Pie Shake Make", :people_limit => 20, :description => "Make pies with Chile Pies and Creamery", :menu_pdf => nil, :menu_text => nil, :date => "2013-07-20", :cost => 35.0, :length => nil, :other_info => nil, :created_at => "2013-07-14 00:20:59", :updated_at => "2013-07-14 00:20:59", :host_id => 7, :blurb => nil, :time => "2000-01-01 19:00:00" }
], :without_protection => true )



Follow.create([
  { :user_id => nil, :followable_id => nil, :followable_type => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Guest.create([
  { :first_name => nil, :last_name => nil, :email => nil, :ticket_id => nil, :event_id => nil, :user_id => nil, :token => nil, :created_at => nil, :updated_at => nil, :charge_id => nil }
], :without_protection => true )



Image.create([
  { :image => "https://www.filepicker.io/api/file/C8WRUJspThSWBGQ9MsqA", :created_at => "2013-07-17 18:14:06", :updated_at => "2013-07-17 18:14:06", :title => nil, :description => nil, :imageable_id => 1, :imageable_type => "SurveyAnswer" },
  { :image => "https://www.filepicker.io/api/file/C8WRUJspThSWBGQ9MsqA", :created_at => "2013-07-17 18:15:50", :updated_at => "2013-07-17 18:15:50", :title => nil, :description => nil, :imageable_id => 2, :imageable_type => "SurveyAnswer" },
  { :image => "https://www.filepicker.io/api/file/C8WRUJspThSWBGQ9MsqA", :created_at => "2013-07-17 18:16:02", :updated_at => "2013-07-17 18:16:02", :title => nil, :description => nil, :imageable_id => 3, :imageable_type => "SurveyAnswer" },
  { :image => "https://www.filepicker.io/api/file/C8WRUJspThSWBGQ9MsqA", :created_at => "2013-07-17 18:16:12", :updated_at => "2013-07-17 18:16:12", :title => nil, :description => nil, :imageable_id => 4, :imageable_type => "SurveyAnswer" },
  { :image => "https://www.filepicker.io/api/file/C8WRUJspThSWBGQ9MsqA", :created_at => "2013-07-17 18:16:25", :updated_at => "2013-07-17 18:16:25", :title => nil, :description => nil, :imageable_id => 5, :imageable_type => "SurveyAnswer" },
  { :image => "https://www.filepicker.io/api/file/C8WRUJspThSWBGQ9MsqA", :created_at => "2013-07-17 18:16:35", :updated_at => "2013-07-17 18:16:35", :title => nil, :description => nil, :imageable_id => 6, :imageable_type => "SurveyAnswer" },
  { :image => "https://www.filepicker.io/api/file/C8WRUJspThSWBGQ9MsqA", :created_at => "2013-07-17 22:47:09", :updated_at => "2013-07-17 22:47:09", :title => nil, :description => nil, :imageable_id => 7, :imageable_type => "SurveyAnswer" }
], :without_protection => true )



Investment.create([
  { :user_id => nil, :project_id => nil, :amount => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Location.create([
  { :address1 => "1680 McAllister Street", :address2 => nil, :city => "San Francisco", :state => "California", :zipcode => "94115", :created_at => "2013-07-14 00:20:59", :updated_at => "2013-07-14 00:20:59", :user_id => nil, :event_id => 1, :neighborhood => "NoPa", :location_title => nil }
], :without_protection => true )



Profile.create([
  { :blurb => "I'm cool", :location_id => 1, :story => "I'm just a foodie", :home_zip => "08873", :work_zip => nil, :user_id => 12, :created_at => "2013-07-14 02:06:42", :updated_at => "2013-07-14 02:07:55", :biz_name => nil, :yelp_id => nil, :neighborhood => nil }
], :without_protection => true )



Project.create([
  { :user_id => nil, :name => nil, :logo => nil, :location => nil, :description => nil, :target => nil, :raised => nil, :terms => nil, :min_investment => nil, :created_at => nil, :updated_at => nil, :business_plan => nil, :category => nil, :approved => nil }
], :without_protection => true )



Signup.create([
  { :email => nil, :chef => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



SurveyAnswer.create([
  { :survey_question_id => 2, :text => "Nopa", :created_at => "2013-07-17 00:42:08", :updated_at => "2013-07-17 00:42:08" },
  { :survey_question_id => 2, :text => "State Bird Provisions", :created_at => "2013-07-17 00:42:23", :updated_at => "2013-07-17 00:42:23" },
  { :survey_question_id => 2, :text => "AQ", :created_at => "2013-07-17 00:42:28", :updated_at => "2013-07-17 00:42:28" },
  { :survey_question_id => 2, :text => "Super Duper", :created_at => "2013-07-17 00:42:33", :updated_at => "2013-07-17 00:42:33" },
  { :survey_question_id => 2, :text => "Frances", :created_at => "2013-07-17 00:50:31", :updated_at => "2013-07-17 00:50:31" },
  { :survey_question_id => 2, :text => "Papito", :created_at => "2013-07-17 22:46:05", :updated_at => "2013-07-17 22:46:05" }
], :without_protection => true )



SurveyQuestion.create([
  { :question => "What type of event would you be most excited about?", :created_at => "2013-07-16 05:03:45", :updated_at => "2013-07-16 05:55:44", :topic => "EventType", :low_extreme => "small", :high_extreme => "large", :format => "slider", :active => true, :for_chef => false },
  { :question => "Which restaurants do you like?", :created_at => "2013-07-17 00:39:38", :updated_at => "2013-07-17 00:39:38", :topic => "Cuisine", :low_extreme => nil, :high_extreme => nil, :format => "option", :active => true, :for_chef => false }
], :without_protection => true )



Ticket.create([
  { :user_id => nil, :event_id => nil, :num_guests => nil, :created_at => nil, :updated_at => nil, :total_paid => nil, :charge_id => nil }
], :without_protection => true )



User.create([
  { :first_name => "neeharika", :last_name => "bhartiya", :approved => false, :created_at => "2013-07-13 00:32:10", :updated_at => "2013-07-16 05:36:01", :email => "neeharika.b@gmail.com", :encrypted_password => "$2a$10$hvLGBg8eOaBZqJffVDbSzOm0ATTmZ5rLoCKob1ygJTla1.knFeXva", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 3, :current_sign_in_at => "2013-07-14 19:35:20", :last_sign_in_at => "2013-07-14 19:34:35", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :completed => false, :chef => false },
  { :first_name => "neeharika", :last_name => "bhartiya", :approved => false, :created_at => "2013-07-13 03:00:04", :updated_at => "2013-07-16 05:36:01", :email => "neeharika.b+1@gmail.com", :encrypted_password => "$2a$10$LIkD3aSCXjIVN93iLy6DzOyN2Hr/3CNjvLObNGANvsDjCEmDkyK7i", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 1, :current_sign_in_at => "2013-07-13 03:00:04", :last_sign_in_at => "2013-07-13 03:00:04", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :completed => false, :chef => false },
  { :first_name => "neeharika", :last_name => "bhartiya", :approved => false, :created_at => "2013-07-13 03:06:46", :updated_at => "2013-07-16 05:36:01", :email => "neeharika.b+2@gmail.com", :encrypted_password => "$2a$10$Jvl4qfHIKu9Y7WnGRmfvhuE1L2zBB3WUYgvOQDdcMMcCU5JZULB.O", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 1, :current_sign_in_at => "2013-07-13 03:06:46", :last_sign_in_at => "2013-07-13 03:06:46", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :completed => false, :chef => false },
  { :first_name => "neeharika", :last_name => "bhartiya", :approved => false, :created_at => "2013-07-13 03:16:11", :updated_at => "2013-07-16 05:36:01", :email => "neeharika.b+3@gmail.com", :encrypted_password => "$2a$10$K4pmf0l4Mt63dTmYQpWx2..GYYGZXSQYAj.hm5o0V7diN2wjBdh8.", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 1, :current_sign_in_at => "2013-07-13 03:16:11", :last_sign_in_at => "2013-07-13 03:16:11", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :completed => false, :chef => false },
  { :first_name => "neeharika", :last_name => "bhartiya", :approved => false, :created_at => "2013-07-13 03:25:39", :updated_at => "2013-07-16 05:36:01", :email => "neeharika.b+4@gmail.com", :encrypted_password => "$2a$10$Jrnu0kq0DJhUzzyyJ17L3.P2lazEJsaBJLjGhPh8Rjy6aABu6wQGm", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 1, :current_sign_in_at => "2013-07-13 03:25:39", :last_sign_in_at => "2013-07-13 03:25:39", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :completed => false, :chef => false },
  { :first_name => "neeharika", :last_name => "bhartiya", :approved => false, :created_at => "2013-07-13 03:37:31", :updated_at => "2013-07-16 05:36:01", :email => "neeharika.b+5@gmail.com", :encrypted_password => "$2a$10$oN7euIm/kICykSYpJj637eQeRkJ6XroGAD1aYJksFEgvADOExGiei", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 1, :current_sign_in_at => "2013-07-13 03:37:31", :last_sign_in_at => "2013-07-13 03:37:31", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :completed => false, :chef => false },
  { :first_name => "neeharika", :last_name => "bhartiya", :approved => false, :created_at => "2013-07-13 03:42:14", :updated_at => "2013-07-16 05:36:01", :email => "neeharika.b+6@gmail.com", :encrypted_password => "$2a$10$CIlihtJzHcTa5m/Iy0JnS.6rkhFcEIZKtDtqdLQT2bsenbhn/VFZO", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 1, :current_sign_in_at => "2013-07-13 03:42:14", :last_sign_in_at => "2013-07-13 03:42:14", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :completed => false, :chef => false },
  { :first_name => "neeharika", :last_name => "bhartiya", :approved => false, :created_at => "2013-07-14 00:59:07", :updated_at => "2013-07-16 05:36:01", :email => "neeharika.b+7@gmail.com", :encrypted_password => "$2a$10$KGESop97DYUgdkbX8JBPUuipzeQ11qT34NKgaAYyyRBgyJmjVqTeW", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 1, :current_sign_in_at => "2013-07-14 00:59:07", :last_sign_in_at => "2013-07-14 00:59:07", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :completed => false, :chef => false },
  { :first_name => "neeharika", :last_name => "bhartiya", :approved => false, :created_at => "2013-07-14 01:11:38", :updated_at => "2013-07-16 05:36:01", :email => "neeharika.b+8@gmail.com", :encrypted_password => "$2a$10$TrktPdCFPafZRthz7ItfEOTz9FI.cU9DZ0MZVW5dPKC7Qnb3R1dpy", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 1, :current_sign_in_at => "2013-07-14 01:11:38", :last_sign_in_at => "2013-07-14 01:11:38", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :completed => false, :chef => false },
  { :first_name => "n", :last_name => "b", :approved => false, :created_at => "2013-07-14 01:24:23", :updated_at => "2013-07-16 05:36:01", :email => "neeharika.b+9@gmail.com", :encrypted_password => "$2a$10$zVUf/4dTOO6dPtnhKjt2WeTQvJYlXKihOjsqvTm4eYfr5gvgPzD2C", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 1, :current_sign_in_at => "2013-07-14 01:24:23", :last_sign_in_at => "2013-07-14 01:24:23", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :completed => false, :chef => false },
  { :first_name => "neeharika", :last_name => "bhartiya", :approved => false, :created_at => "2013-07-14 01:37:47", :updated_at => "2013-07-16 05:36:01", :email => "neeharika.b+10@gmail.com", :encrypted_password => "$2a$10$H5i/J.4F7D0T02w788AORuaxn2hVndpTCLw7c1a0mbV8S/7PwQUt.", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 1, :current_sign_in_at => "2013-07-14 01:37:47", :last_sign_in_at => "2013-07-14 01:37:47", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :completed => false, :chef => false },
  { :first_name => "neeharika", :last_name => "bhartiya", :approved => false, :created_at => "2013-07-14 01:39:36", :updated_at => "2013-07-16 05:36:01", :email => "neeharika.b+11@gmail.com", :encrypted_password => "$2a$10$dg.5.NT6AU067h8pLewtsONU0t6cKbyGBlMLfIcYT6uEtkMZ/Fdea", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 2, :current_sign_in_at => "2013-07-14 02:05:10", :last_sign_in_at => "2013-07-14 01:39:36", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :completed => false, :chef => false },
  { :first_name => "neeharika", :last_name => "bhartiya", :approved => false, :created_at => "2013-07-14 01:50:59", :updated_at => "2013-07-16 05:36:01", :email => "neeharika.b+12@gmail.com", :encrypted_password => "$2a$10$/mLftVbHL6UuHO6k04JbOeKYba8.HRRxXXL2QIcijhNw42068sshK", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 1, :current_sign_in_at => "2013-07-14 01:50:59", :last_sign_in_at => "2013-07-14 01:50:59", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :completed => false, :chef => false }
], :without_protection => true )



UserAnswer.create([
  { :user_id => nil, :survey_question_id => nil, :text => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )


